apiVersion: v2
name: cluster-secret
description: ClusterSecret Operator
kubeVersion: '>= 1.25.0-0'
type: application
version: 2.1.0
icon: https://clustersecret.com/assets/csninjasmall.png
sources:
- https://github.com/tr-aheiev/ClusterSecret
appVersion: "2.1.0"
maintainers:
- email: zakkg3@gmail.com
  name: zakkg3
