# Docker build images on PR
name: Test Builds Images
on: [pull_request]

env:
  IMAGE_TAGS: ${{  github.ref_name }}
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-amd64:
    name: Build amd64
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install qemu dependency
        # we need quemu-user-static for builds other archs with buildah
        # https://github.com/containers/podman/issues/13924#issuecomment-1103434554
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build amd64
        id: build_image_amd64
        uses: redhat-actions/buildah-build@main
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          platforms: linux/amd64
          containerfiles: |
            ./Dockerfile.gh

  build-386:
    name: Build 386
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install qemu dependency
        # we need quemu-user-static for builds other archs with buildah
        # https://github.com/containers/podman/issues/13924#issuecomment-1103434554
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Build 386
        id: build_image_386
        uses: redhat-actions/buildah-build@main
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          platforms: linux/386
          containerfiles: |
            ./Dockerfile.gh

  build-s390:
    name: Builds 390
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install qemu dependency
        # we need quemu-user-static for builds other archs with buildah
        # https://github.com/containers/podman/issues/13924#issuecomment-1103434554
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          sudo apt-get install -y rustc

      - name: Build s390x
        id: build_image_s390x
        uses: redhat-actions/buildah-build@main
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          platforms: linux/s390x
          containerfiles: |
            ./Dockerfile.gh

  build-armv8:
    name: Build armv8
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install qemu dependency
        # we need quemu-user-static for builds other archs with buildah
        # https://github.com/containers/podman/issues/13924#issuecomment-1103434554
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          sudo apt-get install -y rustc

      - name: Build arm64v8
        id: build_image_arm64v8
        uses: redhat-actions/buildah-build@main
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          platforms: linux/arm64/v8
          containerfiles: |
            ./Dockerfile.gh

  build-armv7:
    name: Build armv7
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install qemu dependency
        # we need quemu-user-static for builds other archs with buildah
        # https://github.com/containers/podman/issues/13924#issuecomment-1103434554
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static
          sudo apt-get install -y rustc

      - name: Build armv7
        id: build_image_armv7
        uses: redhat-actions/buildah-build@main
        with:
          image: ${{ env.IMAGE_NAME }}
          tags: ${{ env.IMAGE_TAGS }}
          platforms: linux/arm/v7
          containerfiles: |
            ./Dockerfile-others.gh
